apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-app-pipeline
description: "Delivery pipeline for Flask app"
serialPipeline:
  stages:
    - targetId: dev
    - targetId: staging
    - targetId: production