apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: flask-app
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/project-bct-463501/flask-repo/flask-app
    context: app
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
      paths:
        - "*.yaml"

profiles:
  - name: clouddeploy
    deploy:
      cloudrun: {}