apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: flask-app-pipeline
description: Multi-stage pipeline for Flask app
serialPipeline:
  stages:
    - targetId: dev
    - targetId: staging
    - targetId: production
      strategy:
        standard:
          verify: true